### ISSUE TITLE
webservice not running in docker desktop on windows

### ISSUE THREAD

**Issue by darshanhurix** [adlnet/CATAPULT#21]
Hi All,

We have been struggling getting the CTS up and running, the player and rdbms services are running fine but not able to start webserivce

**[dumb-init] ./entrypoint.sh: No such file or directory**
![containers](https://user-images.githubusercontent.com/91274943/141320633-43b2df6c-9cc4-451a-8d90-ad47ccd7a7c5.png)
![log](https://user-images.githubusercontent.com/91274943/141320686-b8cec66a-36bd-4fa9-9225-1e2a716b0a19.png)

Any help would help my team to upload and test the sample cmi5 packages

**Comment by gavbaa** [comment]
Your checkout was probably done with git configured to change line endings ("\n") to Windows endings ("\r\n").  The way to fix this is: 
```
git config --global core.autocrlf input
```

See more here: https://stackoverflow.com/questions/38905135/why-wont-my-docker-entrypoint-sh-execute

I was able to recreate it with git default configs on a Windows test box, and then deleted the repo, ran this git command, and then re-checked out fresh.  Everything launched correctly after that.

**Comment by darshanhurix** [comment]
Thanks that worked, 

Now after uploading a sample single au course i am getting the following error Failed to load learner preferences

![image](https://user-images.githubusercontent.com/91274943/141409964-87e408ab-f570-467e-911b-fc3f4abda07c.png)

**Comment by darshanhurix** [comment]
When the request is made to get the learner pref to http://localhost:63399/api/v1/tests/5/learner-prefs

{
	"statusCode": 500,
	"error": "Internal Server Error",
	"message": "An internal server error occurred",
	"srcError": "Failed to request learner preferences from player (500): An internal server error occurred (Failed request to retrieve learner preferences: Error: Client request error: connect ECONNREFUSED 127.0.0.1:80)"
}

This error is received

**Comment by brianjmiller** [comment]
You probably have your `LRS_ENDPOINT` configured to point to 127.0.0.1 but it has to be the address as it can be seen *from inside the container* so the localhost IP won't work from inside the private network created by docker compose. You'd need to use an address similar to `http://host.docker.internal:80` plus any path to the LRS.

**Comment by darshanhurix** [comment]
Hi Brian

These are my configuration

SQL_PORT=3306
HOST_PORT=63399
PLAYER_HOST_PORT=63398
PLAYER_CONTENT_URL=http://localhost:63398/content
PLAYER_KEY='apikey'
PLAYER_SECRET="APIsecret"
PLAYER_TOKEN_SECRET="asdasdasdasd"
LRS_ENDPOINT="http://local.veracity.it/testlrs/xapi/"
LRS_USERNAME="darshan"
LRS_PASSWORD="password"

and my LRS is running on http://local.veracity.it which is again local port 80 👍 

Can you please suggest what needs to be done so as to access LRS

**Comment by gavbaa** [comment]
@darshanhurix You'll probably want to switch the LRS endpoint to "host.docker.internal" instead of local.veracity.it , as Docker Desktop does host networking a bit special.  See more at https://docs.docker.com/desktop/windows/networking/ , under "I want to connect from a container to a service on the host".

**Comment by darshanhurix** [comment]
Thanks team solved
