### ISSUE TITLE
LTS: 005-1-invalid-au.zip: send statement after terminated

### ISSUE THREAD

**Issue by cars10** [adlnet/CATAPULT#23]
In https://github.com/adlnet/CATAPULT/blob/main/lts/pkg/src/005-1-invalid-au/005-1-invalid-au.js#L763 we send the same Statement as in https://github.com/adlnet/CATAPULT/blob/main/lts/pkg/src/005-1-invalid-au/005-1-invalid-au.js#L345 again.

[Per the xAPI spec](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#211-put-statements):

> An LRS MUST NOT make any modifications to its state based on receiving a Statement with a statementId that it already has a Statement for. Whether it responds with 409 Conflict or 204 No Content, it MUST NOT modify the Statement or any other Object.

We currently return a `409 Conflict` but the CATAPULT Testsuite fails here.

**Comment by gavbaa** [comment]
It's inappropriate to respond to that statement as a 409, as the second statement on L763 has occurred after a valid terminate of the cmi5 session.  This means the credentials are no longer valid for the cmi5 session and the statement should never be allowed to be validated against another statement to even identify a conflict.  Probably a 401 response from your LMS is more appropriate here.

**Comment by cars10** [comment]
My bad, i missed the `terminated` in the previous step. Thanks!
