### ISSUE TITLE
Question about lts "essentials" package

### ISSUE THREAD

**Issue by cawerkenthin** [adlnet/CATAPULT#29]
Why does the cmi5.xml for the "essentials" package use CDATA for the au url?  What is the associated spec requirement?

**Comment by brianjmiller** [comment]
IIRC the `&` is the problem. The normal way to escape it in the body of an element would be to switch to `&amp;` but in this case we need the URL to stay intact as a URL. We use those params to test the requirement around merging of query string parameters, 13.1.4.0-3.

**Comment by cawerkenthin** [comment]
OK, thanks.  More curiosity than anything else.
