### ISSUE TITLE
CTS should populate learner preferences even if they're empty defaults

### ISSUE THREAD

**Issue by LiamKearn** [adlnet/CATAPULT#48]
Part of the content specification outlines that `The AU MUST retrieve the Learner Preferences document from the Agent Profile on startup.`.

The tester shouldn't need to setup the agent profile in the `client/#/test/{ID}` route. It should automatically at least put a "default" document when then agent is created (new test in the CTS).

**Comment by brianjmiller** [comment]
The spec requires that the AU request the learner preferences *but* it does not indicate that one must exist. It would not be a good assumption to make that an agent profile exists, forcing a default into catapult would give this impression.

**Comment by LiamKearn** [comment]
Excellent, Thanks for the clarification @brianjmiller I just added a switch to ignore not found errors which is enabled by default in our AU impl. Perfect :)
