### ISSUE TITLE
Course Test Suite (CTS): Mastery score override able to go out of bounds.

### ISSUE THREAD

**Issue by matty-articulate** [adlnet/CATAPULT#6]
Hi all,

Love the CTS, and it's great fun to use! While using it though I did come across the following oddity regarding setting mastery scores in the CTS test configuration screen (before you launch the course being tested). Please let me know if any additional details or information is needed!

Thank you.

## Potential Issue Description 🔍 
When modifying the AU's `Mastery Score` via the CTS it's possible to set the value beyond the expected [0~1 threshold](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#masteryscore).

For example, accidentally setting a Mastery Score to 90 (instead of a valid 0.9) will result in a test package's passing percentage to effectively be 9,000% instead of 90%, with no errors or issues exposed by the CTS.
<img src="https://user-images.githubusercontent.com/61706283/134434963-7decddff-5418-4a2b-ab05-c3fd890c52ed.png" width=50% height=50%>

## Replication Steps 🔢 
1. Either create, or access an existing course within the CTS with content that accepts and handles LMS modified mastery scores.
2. Either create, or access an existing test for the course.
3. In the `Assignable Units` section click on the `Show Configuration` toggle.
4. Enter a value greater than 1 for the `Mastery Score`
5. Launch the course content and take the quiz as expected. If authoring content does not have a handler for dealing with out-of-bound values provided by the LMS then it can result in bad passing requirements being passed to the test course.

Example screenshot of setting mastery score configuration value to 90.
<img src="https://user-images.githubusercontent.com/61706283/134437534-9c96fd4c-8a24-4fd0-bc23-0e2d3cac9a0d.png" width=50% height=50%>

## Test cmi5 Package 📦 
[Rise 360 cmi5 test course package](https://github.com/adlnet/CATAPULT/files/7214476/qa-auto-test-123-arba-1-g-34-b-cmi5-6JRH6vxo.zip)

## Documentation 📚
[cmi5 Mastery Score specification](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#masteryscore)
[CTS User Guide - Configuration settings](https://adlnet.github.io/CATAPULT/cts/#configuration)

**Comment by gavbaa** [comment]
This should be resolved by the merge of #6.  Please let us know if that fully addresses the issue.

**Comment by matty-articulate** [comment]
Hi there!

Confirmed: No longer able to send values that are out of bounds! Doing so results in an expected error message. Would be awesome to be a bit more verbose on what the exact error is, but it works. :)

![image](https://user-images.githubusercontent.com/61706283/135487638-8a265ed4-1ca5-47a2-aa37-4e8da22db42a.png)
